"""create workspaces

Revision ID: 2f7910c9387f
Revises: 8d05be328dd8
Create Date: 2026-07-11 19:24:43.686967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7910c9387f'
down_revision: Union[str, Sequence[str], None] = '8d05be328dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create workspaces table
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_index(
        op.f("ix_workspaces_id"),
        "workspaces",
        ["id"],
    )

    op.create_index(
        op.f("ix_workspaces_slug"),
        "workspaces",
        ["slug"],
        unique=True,
    )

    # 1. Add column as nullable
    op.add_column(
        "users",
        sa.Column(
            "workspace_id",
            sa.Integer(),
            nullable=True,
        ),
    )

    # 2. Create default workspace
    op.execute("""
        INSERT INTO workspaces (name, slug, created_at)
        VALUES ('Default Workspace', 'default', NOW())
    """)

    # 3. Assign existing users
    op.execute("""
        UPDATE users
        SET workspace_id = (
            SELECT id
            FROM workspaces
            WHERE slug='default'
        )
    """)

    # 4. Make column NOT NULL
    op.alter_column(
        "users",
        "workspace_id",
        nullable=False,
    )

    # 5. Add foreign key
    op.create_foreign_key(
        "fk_users_workspace",
        "users",
        "workspaces",
        ["workspace_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "fk_users_workspace",
    "users",
    type_="foreignkey",
)
    op.drop_column('users', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
